name: Deploy to Development and Production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "${{ secrets.APPLICATION_PROD }}" >> ./application.yml
          else
            echo "${{ secrets.APPLICATION_DEV }}" >> ./application.yml
          fi
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker Build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            IMAGE_TAG="juulabel_backend"
          else
            IMAGE_TAG="juulabel_dev_backend"
          fi
          docker build -t ${{ secrets.DOCKER_REPO }}/$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_REPO }}/$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ dev, prod ]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ matrix.environment == 'prod' && secrets.HOST_PROD || secrets.HOST_DEV }}
          username: ubuntu
          key: ${{ matrix.environment == 'prod' && secrets.KEY_PROD || secrets.KEY_DEV }}
          port: 22
          script: |
            if [ "${{ matrix.environment }}" == "prod" ]; then
              IMAGE_TAG="juulabel_backend"
            else
              IMAGE_TAG="juulabel_dev_backend"
            fi
            sudo docker pull ${{ secrets.DOCKER_REPO }}/$IMAGE_TAG
            sudo docker compose down
            sudo docker compose up -d


            if sudo docker ps -q --filter "name=spring_green"; then # 현재 실행 중인 컨테이너가 Green인지 Blue인지 확인
              echo "Spring Green is up, switching traffic to Blue."
              sudo sed -i 's/spring_green:8080/spring_blue:8080/' /etc/nginx/nginx.conf # 현재 Green이 실행 중이라면 Blue에 새로운 버전 배포
              sudo nginx -s reload # 트래픽을 Blue로 전환
            
              sudo docker pull ${{ secrets.DOCKER_REPO }}/$IMAGE_TAG # 새로운 버전을 Blue에 배포
              sudo docker compose up -d spring_blue
            
            
              if sudo docker ps -q --filter "name=spring_blue"; then # 새로운 버전이 정상적으로 실행되는지 확인
                echo "Spring Blue is up, deployment successful!"
              else
                echo "Error in Blue deployment, rolling back to Green."
            
                sudo sed -i 's/spring_blue:8080/spring_green:8080/' /etc/nginx/nginx.conf # Blue 배포가 실패하면, Green으로 롤백
                sudo nginx -s reload
                exit 1
              fi
            else
              echo "Spring Blue is up, switching traffic to Green."
              sudo sed -i 's/spring_blue:8080/spring_green:8080/' /etc/nginx/nginx.conf # 현재 Blue가 실행 중이라면 Green에 새로운 버전 배포
              sudo nginx -s reload # 트래픽을 Green으로 전환
            
              sudo docker pull ${{ secrets.DOCKER_REPO }}/$IMAGE_TAG # 새로운 버전을 Green에 배포
              sudo docker compose up -d spring_green
            
            
              if sudo docker ps -q --filter "name=spring_green"; then # 새로운 버전이 정상적으로 실행되는지 확인
                echo "Spring Green is up, deployment successful!"
              else
                echo "Error in Green deployment, rolling back to Blue."
            
                sudo sed -i 's/spring_green:8080/spring_blue:8080/' /etc/nginx/nginx.conf # Green 배포가 실패하면, Blue로 롤백
                sudo nginx -s reload
                exit 1
              fi
            fi

        if: |
          (matrix.environment == 'prod' && github.ref == 'refs/heads/main') ||
          (matrix.environment == 'dev' && github.ref != 'refs/heads/main')
